openapi: 3.0.0
info:
  title: API di Esempio
  description: Questa è un'API di esempio per il tuo plugin.
  version: 1.0.0
servers:
  - url: https://ascanick.github.io/testRepo
paths:
  /data.json:
    get:
      summary: Recupera dati
      description: Recupera dati dall'API di esempio.
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        user:
                          type: string
                        message:
                          type: string
                        timestamp:
                          type: string
                          format: date-time
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        email:
                          type: string