openapi: 3.0.0
info:
  title: API di Esempio
  description: Questa è un'API di esempio per il tuo plugin.
  version: 1.0.0
servers:
  - url: https://api.example.com
paths:
  /data:
    get:
      summary: Recupera dati
      description: Recupera dati dall'API di esempio.
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Dati recuperati con successo"